
on:
   push:
    branches:
    - main
    - release/*
   pull_request:
    branches:
    - main

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: cd-runner

    steps:
    
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
         name: CICDPublish

    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./CICDPublish/* C:/inetpub/wwwroot/cicdprac -Recurse -Force
        iisreset /start
    
    - name: Curl the website as a smoke test
      run: curl http://localhost/cicdprac

    
