name: Deploy Development
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    name:  Development Build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore /p:DebugType=None
    
    - name: Publish
      run: dotnet publish CICDPracticalRepo/CICDPracticalRepo.csproj -o PublishDev/CICDPracticalRepo/ -r win-x64 --self-contained false /p:DebugType=None
    
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
        
    #- name: Upload Application Publish Artifact
    - uses: actions/upload-artifact@v2
      with:
        name: DevCICDPublish        
        path: PublishDev/CICDPracticalRepo/

