name: Deploy Development
on:
  push:
    branches: [ development ]

jobs:
  build:
    name:  Development Build
    runs-on: cicd-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
  
    #- name: Cache node modules
    #- uses: actions/cache@v2
    #  with:
    #    path: | 
    #          ~/.nuget/packages
    #          !~/.nuget/packages/unwanted
    #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    #    restore-keys: |
    #                  ${{ runner.os }}-nuget-
    #- name: Dotnet Restore
    #  if: steps.cache.outputs.cache-hit != 'true'
    #  run: nuget restore CICDPracticalRepo.sln
  
    - name: Build
      run: dotnet build --configuration Debug --no-restore /p:DebugType=None
    
    #- name: Publish
    #  run: dotnet publish CICDPracticalRepo/CICDPracticalRepo.csproj -c Release -f netcoreapp3.1 --no-build --no-restore -o PublishDev/CICDPracticalRepo/ -r win-x64 --self-contained false /p:DebugType=None
  
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
        
    #- name: Upload Application Publish Artifact
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: DevCICDPublish        
    #    path: PublishDev/CICDPracticalRepo/

