name: Deploy Production
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  release:
    types: [created]

jobs:
  build:
    name:  Production Build
    runs-on: windows-latest
    env:
      IIS_SERVER_COMPUTER_NAME: "ec2-15-206-122-222.ap-south-1.compute.amazonaws.com"
      IIS_WEBSITE_NAME: "cicdprac"
      IIS_SERVER_USERNAME: 'EC2AMAZ-IAFNI1E\WDeployAdmin'
      IIS_SERVER_PASSWORD: "=D5taal4Gtzum9*Rmw9ZIKj=EvDWdl)Q"
      RECYCLE_APP_NAME: "cicdprac"
      WEBSITE_CONTENT_PATH: 'C:\inetpub\wwwroot\cicdprac'
    
    steps:
#    - uses: actions/checkout@v2
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.301
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --configuration Release --no-restore /p:DebugType=None
    
#    - name: Publish
#      run: dotnet publish CICDPracticalRepo/CICDPracticalRepo.csproj -o PublishPro/CICDPracticalRepo/ -r win-x64 --self-contained false /p:DebugType=None
  
        
   # - name: Stop Application Pool
   #   shell: cmd
   #   run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ env.RECYCLE_APP_NAME }}",recycleMode="StopAppPool",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"'
    - name: Deploy Application
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="D:\a\CICDPracticalRepo\CICDPracticalRepo\PublishPro\CICDPracticalRepo\" -dest:contentPath="${{ env.WEBSITE_CONTENT_PATH }}",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",authtype="Basic"'
    - name: Start Application Pool
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ env.RECYCLE_APP_NAME }}",recycleMode="StartAppPool",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"'
