name: Deploy Production
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  release:
    types: [created]

jobs:
  build:
    name:  Production Build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:DebugType=None
    
    - name: Publish
      run: dotnet publish CICDPracticalRepo/CICDPracticalRepo.csproj -o PublishPro/CICDPracticalRepo/ -r win-x64 --self-contained false /p:DebugType=None
  

    - name: GitHub Actions WebDeploy
    # You may pin to the exact commit or the version.
    # uses: cschleiden/webdeploy-action@48a2cdaf8aaa2bc762c12948ada3db14faead320
      uses: cschleiden/webdeploy-action@v1
      with:
      # Name of an existing website on the IIS machine
        webSiteName: cicdprac
      # File path to the package or a folder generated by MSBuild or a compressed archive file.
        package: PublishPro/CICDPracticalRepo/
      # (Optional) Select the option to delete files on the Web App that have no matching files in the Web App zip package.
      #  removeAdditionalFilesFlag: # optional
      # (Optional) Select the option to take the Web App offline by placing an app_offline.htm file in the root directory of the Web App before the sync operation begins. The file will be removed after the sync operation completes successfully.
      #  takeAppOfflineFlag: # optional
