name: Deploy Production
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    name:  Production Build
    runs-on: windows-latest
    env:
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_WEBSITE_NAME: ${{ secrets.IIS_WEBSITE_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      RECYCLE_APP_NAME: ${{ secrets.RECYCLE_APP_NAME }}
      WEBSITE_CONTENT_PATH: ${{ secrets.WEBSITE_CONTENT_PATH }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -r win-x64 /p:DebugType=None
    
    - name: Publish
      run: dotnet publish CICDPracticalRepo/CICDPracticalRepo.csproj -c Release -f netcoreapp3.1 --no-build --no-restore -o PublishPro/CICDPracticalRepo/ -r win-x64 --self-contained true /p:DebugType=None
  
        
    - name: Stop Application Pool
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ env.RECYCLE_APP_NAME }}",recycleMode="StopAppPool",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"'
    - name: Deploy Application to EC2-IIS
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="D:\a\CICDPracticalRepo\CICDPracticalRepo\PublishPro\CICDPracticalRepo\" -dest:contentPath="${{ env.WEBSITE_CONTENT_PATH }}",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",authtype="Basic"'
    - name: Start Application Pool
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ env.RECYCLE_APP_NAME }}",recycleMode="StartAppPool",computerName="${{ env.IIS_SERVER_COMPUTER_NAME }}/msdeploy.axd?site=${{ env.IIS_WEBSITE_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"'
    
    - name: Easy Zip Files
    # You may pin to the exact commit or the version.
    # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: ./PublishPro/CICDPracticalRepo/
        # Name of output zip file
        dest: ./PublishPro/cicd.zip
        # Whether to add subdirectories to simply zip all files to the root
        #recursive: # optional, default is true
      
    - name: Easy Zip Files
    # You may pin to the exact commit or the version.
    # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: ./PublishPro/cicd.zip ./PublishPro/CICDPracticalRepo/aws-windows-deployment-manifest.json
        # Name of output zip file
        dest: ./PublishPro/cicdprac.zip
        # Whether to add subdirectories to simply zip all files to the root
        #recursive: # optional, default is true
      
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYYMMDD    
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: cicdprac-app-bean
        environment_name: Cicdpracappbean-env
        version_label: cicd-prod-${{ steps.current-time.outputs.formattedTime }}
        region: ap-south-1
        deployment_package: D:/a/CICDPracticalRepo/CICDPracticalRepo/PublishPro/cicdprac.zip
        use_existing_version_if_available: true
      

